### ISSUE TITLE
Unrecognized dhcpd on Kali

### ISSUE THREAD

**Issue by blurmonk** [brav0hax/easy-creds#17]
Hi

I installed this on Kali but getting unrecognized dhcpd. As I understand Kali is using isc-dhcp

thanks

**Comment by brav0hax** [comment]
That's already been coded in there over a year ago.

Are you using version 3.8-dev?

Interesting as everything defaults to isc-dhcp-server.

**Comment by blurmonk** [comment]
Hi

I just got the latest master. it says 3.73.Let me retry it.

**Comment by brav0hax** [comment]
Hmmm...yeah v3.8 Dev is latest 3.7.3 is broke.

Pretty sure 3.8-dev was pushed a long time ago.

**Comment by blurmonk** [comment]
Hi

Yeah I uninstalled everything and redid it. You were right, 3.8 works fine.

Thanks again and sorry for the misleading bug.

**Comment by brav0hax** [comment]
No worries at all 3.7.3 was a bad release :(
