### ISSUE TITLE
updates?

### ISSUE THREAD

**Issue by ghost** [brav0hax/easy-creds#18]
Great project, but are you going to make any updates?

**Comment by brav0hax** [comment]
I would love to. It all comes down to time which I have none.

With the new hostapd - wpe I'd like to switch the free radius attack to
that.

Additionally would like to dump airbase and move all wireless to hostapd.

**Comment by ghost** [comment]
cool but i was thinking if you could add in an option to evil twin attack that would have a fake router update like this for example https://imgur.com/T5Sv9rh
